name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_SSH_KEY }}

      - name: Copy files to EC2 - Instance 1 (Prueba2AWS)
        run: |
          scp -o StrictHostKeyChecking=no ./index.html ec2-user@107.21.218.122:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@107.21.218.122 "sudo mv /tmp/index.html /usr/share/nginx/html/index.html && sudo systemctl restart nginx"
    
      - name: Copy files to EC2 - Instance 2 (ASWPrueba3)
        run: |
          scp -o StrictHostKeyChecking=no ./index.html ec2-user@52.44.2.121:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@52.44.2.121 "sudo mv /tmp/index.html /usr/share/nginx/html/index.html && sudo systemctl restart nginx"
      
          