name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_EC2_SSH_KEY }} ec2-user@3.85.119.100 "sudo chmod 777 /usr/share/nginx/html/index.html"
          scp -o StrictHostKeyChecking=no -i ${{ secrets.AWS_EC2_SSH_KEY }} -r ./index.html ec2-user@3.85.119.100:/usr/share/nginx/html/index.html
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_EC2_SSH_KEY }} ec2-user@3.85.119.100 "sudo chmod 644 /usr/share/nginx/html/index.html"